iobio/clin.iobio

- src/components/pages/ClinHome.vue
- src/components/viz/PedigreeGraph.vue
- src/components/viz/ReviewCase.vue
Fixing errors when running clin with demo data, added type checking to make sure components only try to render after the input data props have been populated
> only rendering ReviewCase components when launched from mosaic

- package-lock.json
- package.json
- src/components/pages/ClinHome.vue
> Phenotypist updates

- src/components/viz/BarChart.vue
- src/components/viz/PedigreeGraph.vue
- src/components/viz/QualitativeBarChart.vue
- src/components/viz/ReviewCase.vue
- src/utils/builder.js
Page layout and styling, added correct axis labels and tick labels to BarChart component, added median coverage line to BarChart component, pedigree styling matching frameshift styling, added individual and total variant counts to QualitativeBarChart component, added column headers for visualizations, using correct sample Id, added relationship info to sample column, sorting visualizations by relationship (proband < mother < father < sibling)
> Review page

- package-lock.json
- package.json
- src/components/pages/Workflow.vue
@tonydisera This Pull Request updates/ fixes the following issues: 
- Fix the dark blue circle appearing as part of the badge in workflow 
- Add a "genes overlap" button to show venn diagram visualization 
- Show the number of terms in each tool and number of notes added in badge.
> Phenotypist ui 01152020

- package-lock.json
- package.json
> Consistent height for notes and terms panel

- package-lock.json
- package.json
- src/components/pages/ClinHome.vue
- Adds task badges for phenotypes 
- Shows progress bar on HPO review terms dialog if it takes time to fetch the hpo terms from clinphen 
- Adds powered by Clinphen on HPO terms review dialog
> show task badges for phenotypist

- package-lock.json
- package.json
- Shows note in review term modal 
- Adds an outline to add gene box 
- Clicking Cancel clears out the add gene box
- Hovering over the Venn diagram does not show a pointer
> Phenotypist UI updates 

- src/components/viz/BarChart.vue
- src/components/viz/QualitativeBarChart.vue
- src/components/viz/ReviewCase.vue
Hotfix for NaN variant types, showing total variant count and min coverage threshold on hover with NaN data
> Min coverage hot fix

- src/components/viz/BarChart.vue
- src/components/viz/ReviewCase.vue
Changed min coverage line to black so it is always visible
> changed min coverage line to always be visible

- src/components/pages/WorkflowNav.vue
- src/components/partials/findings/VariantAliasesMenu.vue
- src/components/viz/Findings.vue
- src/components/viz/findings/VariantInspectCard.vue
Fixes the following issues in findings page: 
- Variants section is blank until variants are reviewed
- Way to link back to Review Variants for a variant
- Need to show HGVSp and HGVSc for each variant
> Findings variants section blank

- src/models/MosaicSession.js
resolving notes.user in Mosaic Session so username will display in gene notes
> User in notes hot fix

- src/components/pages/ClinHome.vue
- src/components/pages/WorkflowNav.vue
This pull request changes the information shown in badges on the findings page. 
Issue #123
> Feature review variant badges

- package-lock.json
- package.json
Refer issue #121  for details 
Also, merge the PR #138 before merging this PR. 
The latest version is deployed on http://dev.clin.iobio.io/
> phenotypes group select

- package-lock.json
- package.json
- src/components/pages/WorkflowNav.vue
- src/main.js
This PR fixes the following minor issues. So I have addressed them in single PR.  
#130 : Change text in the dialog box to Yes and No 
#135 Center the navigation workflow lines 
Capitalize the badges. 
You can test it: http://dev.clin.iobio.io/ 
@tonydisera If you are okay with it, I can merge.
> Minor fixes

- src/assets/css/v-tooltip.css
- src/components/pages/ClinHome.vue
- src/components/pages/Navigation.vue
- src/components/viz/BarChart.vue
- src/components/viz/PedigreeGraph.vue
- src/components/viz/ReviewCase.vue
- src/utils/builder.js
- src/utils/dtree.js
Added case description, pedigree, and average coverage to project title dropdown, showing minimum coverage threshold by default, only display min coverage threshold if it is within bounds of the coverage x-axis
> Project title tooltip

- src/components/pages/ClinHome.vue
- src/models/MosaicSession.js
- src/router/index.js
This allows clin.iobio to be launched from Utah Mosaic with gene sets.  See issue #162
> Feature gene sets in clin

- package-lock.json
- package.json
This Pull Request moves the delete gene icon to its separate column and reorders the action buttons in the dialog to show affirmative first.
> moves delete gene icon to separate column

- src/components/pages/ClinHome.vue
Points to the latest 4.0 version of gene.iobio instead of stage.gene.iobio. 
> Point to prod gene.iobio

- package-lock.json
- package.json
- src/components/pages/LandingPage.vue
- src/components/partials/MoreMenu.vue
This Pull request allows users to remove the previously selected phenotypes in edit mode. These terms were disabled in the earlier version. 
> Selected terms edit mode

- package-lock.json
- package.json
- public/index.html
Please refer to issue #186 for more details. 
> Show gene info and chromosome viz in the gene list #186

- package-lock.json
- package.json
@mvelinder , added the following tooltip text on shield icon mouseover:
> Gtr shield icon explanation 

- package-lock.json
- package.json
This PR returns the top 100 genes for each term in phenolyzer. 
To test: 
Go to step 2 and select a term from phenolyzer.  it should not show more than 100 for each term.  Require to do npm install if testing locally. 
Test link: http://dev.clin.iobio.io/
> limit phenolyzer genes to 100

- package-lock.json
- package.json
This should automatically adjust the height of the expansion panels in the dropdown. 
> Dropdown blank height

- src/components/partials/findings/VariantInspectInheritanceRow.vue
Showing the inheritance label for the variant inheritance visualization inside gene iframe
> added inheritance label to inheritance viz for clin

- src/components/pages/ClinHome.vue
- src/components/viz/Findings.vue
- src/components/viz/findings/DrugInfoDialog.vue
- src/components/viz/findings/VariantInspectCard.vue
This PR shows drug information for reviewed variants on the findings page. 
To test: 
- Load clin.iobio with demo data 
- Go to "review variants" 
- Select the variant "SCN8A" and review it. 
- Go to "report findings"   
- Click "Drugs for SCN8A" button 
- Drug information is shown in a dialog. 
- Drugs for gene button is disabled when no drug information is available.
> Add gene drug interaction

- src/components/viz/ReviewCase.vue
More robust pedigree parsing for ped files, now handles any combo of white space separating columns
> more robust ped file parsing

- src/components/viz/ReviewCase.vue
Checking for header when parsing ped file
> checking for header when parsing ped file

- src/components/pages/ClinHome.vue
- src/components/pages/LandingPage.vue
The config file validation error dialog may need to be restyled, and there are still some additional checks that could be theoretically performed, but I think the error checking is sufficiently robust for now, someone would have to really screw around with the produced config files to get through the checks
> improved config file validation checks

- src/components/viz/ReviewCase.vue
Fixed issue where relationships were getting incorrectly mapped to pedigrees when using a user uploaded ped file
> fixed pedigree relationship mapping bug for custom data

- src/components/pages/ClinHome.vue
- src/components/pages/LandingPage.vue
- src/components/partials/BedData.vue
- src/components/partials/FilesDialog.vue
- src/components/viz/ReviewCase.vue
This PR is for the issue: #236 
To test: 
Open the upload data dialog: 
enter project info and ped file> 
In step 3, there is a new field for data type: 
For exome, you can either select a standard bed file or add your own custom bed file. 
For testing purpose, select exome and standard bed file 
Use the following URLs for VCF and BAM. 
https://s3.amazonaws.com/iobio/samples/vcf/platinum-exome.vcf.gz
https://s3.amazonaws.com/iobio/samples/bam/NA12878.exome.bam
Gene set: PRX, SCN8A, DLL4, DVL3
> Input bed file

- src/components/pages/LandingPage.vue
- src/components/viz/ReviewCase.vue
Allows importing a config file that has fields for bam, vcf, and bed files along with pedigree information.
> Input config file

- src/components/viz/ReviewCase.vue
Fixing the issue where only 4 samples were being rendered for larger pedigrees, also fixed issue with sorting by relationship when launched from mosaic
> Review case large pedigree

- package-lock.json
- package.json
- src/components/pages/ClinHome.vue
- src/components/viz/Findings.vue
- src/components/viz/QualitativeBarChart.vue
- src/components/viz/ReviewCase.vue
PR for the issues: #262 #263 #264 #267  #268 
Test- http://dev.clin.iobio.io/
> Demo data style fixes

- src/components/pages/ClinHome.vue
Rendering review case when step is selected to properly render pedigrees
> only render ReviewCase page when that workflow step is selected 

- src/components/pages/ClinHome.vue
- src/components/pages/LandingPage.vue
- src/components/pages/Navigation.vue
- src/store/index.js
Issue: #289 
To test: try with the demo data, and click on the title inside the clin workflow. It should link back to the landing page and the buttons should be updated. 
Click resume and it should take you back to the last checkpoint. 
You can try it on: http://dev.clin.iobio.io/
> Link to homepage

- package-lock.json
- package.json
- src/components/pages/ClinHome.vue
Text on the "No gene set" warning dialog is updated.
> Patch update- 2.1.1 release 

- package-lock.json
- package.json
This PR adds autocomplete when adding genes in the "select phenotype" step.
Issue: https://github.com/iobio/clin.iobio/issues/313
To test: 
- Clone this PR and do `npm install` 
- Launch clin with demo data 
- Go to select phenotypes 
- Text "Find gene" in the search input changed to "Search in gene list" 
- Text on the button "+ Add " changed to "Add gene list" 
- There are two options to add genes: Pasting genes (genes can be a comma, semicolon or space separated) and selecting genes from the input (autocomplete). 
- Multiple genes can be added to both the inputs.
> Add autocomplete to Add Genes functionality #313

- src/components/pages/ClinHome.vue
- src/models/MosaicSession.js
Use new Mosaic api for variant sets.
> April 27, 2022 Meeting https://github.com/iobio/calypso/issues/45

- package-lock.json
- src/components/pages/ClinHome.vue
- src/components/pages/WorkflowNav.vue
> Make changes to support app notifications in gene.iobio

- package.json
- src/components/pages/ClinHome.vue
- src/components/pages/Workflow.vue
- src/components/pages/WorkflowNav.vue
- src/components/partials/AppIcon.vue
- src/components/partials/MoreMenu.vue
- src/components/partials/findings/VariantInterpretationBadge.vue
- src/components/viz/findings/VariantInspectCard.vue
- src/data/analysis.json
- src/globals/GlobalApp.js
- src/models/CohortModel.js
- Variant interpretation 'unknown-sig' is now coded as 'uncertain-sig'.
- Add 'About' to more menu, showing clin.iobio version and release date
- Take out 'WARS1' gene workaround.
> Clin 3.3.1
